[package]
name = "rust-cli-todo"
version = "0.1.0"
edition = "2024"

[dependencies]

clap = { version = "4", features = ["derive"] }   # for parsing CLI arguments
serde = { version = "1", features = ["derive"] } # for serialization
serde_json = "1"  